export type ControlStatus =
  | "Certified"
  | "Due soon"
  | "Evidence needed"
  | "Overdue"
  | "Unassigned"
  | "Not started";

export type InventoryControl = {
  id: string;
  name: string;
  process: string;
  frequency: string;
  keyControl: boolean;
  nature: "Preventive" | "Detective";
  type: string;
  evidenceRequired: boolean;
  owner: string;
  status: ControlStatus;
  due: string;
  dtpStatus: "Current" | "Needs review" | "Not added";
  region: string;
  site: string;
  unit: string;
  instructions: string;
};

const controlRows: Array<
  [string, string, string, string, boolean, "Preventive" | "Detective", string]
> = [
  [
    "INV.MF.01",
    "Creation and Changes to Bill of Materials",
    "Manufacturing",
    "Event Based",
    true,
    "Preventive",
    "Manual with IT Dependency",
  ],
  [
    "INV.MF.02",
    "Production Plan Creation and Review",
    "Manufacturing",
    "Periodic",
    false,
    "Preventive",
    "Manual",
  ],
  [
    "INV.MF.03",
    "Inventory Production Consumption",
    "Manufacturing",
    "Event Based",
    true,
    "Preventive",
    "Automated",
  ],
  [
    "INV.RV.01",
    "Physical Access",
    "Receiving",
    "Event Based",
    false,
    "Preventive",
    "Manual",
  ],
  [
    "INV.RV.02",
    "Review of Physical Access",
    "Receiving",
    "Annually",
    false,
    "Detective",
    "Manual",
  ],
  [
    "INV.RV.03",
    "Goods Received by an Appropriate Associate",
    "Receiving",
    "Event Based",
    true,
    "Preventive",
    "Manual",
  ],
  [
    "INV.RV.04",
    "Goods Received Three-Way Match",
    "Receiving",
    "Event Based",
    true,
    "Preventive",
    "Manual",
  ],
  [
    "INV.PE.01",
    "Period End Inventory Cut-off Review",
    "Period End",
    "Quarterly",
    true,
    "Preventive",
    "Manual",
  ],
  [
    "INV.PE.02",
    "Supply Financial KPI Review",
    "Period End",
    "Periodic",
    false,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.PE.03",
    "Purchase Price Variance (PPV) Analysis",
    "Period End",
    "Periodic",
    false,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.PE.04",
    "Materials Usage Variance (MUV) Analysis",
    "Period End",
    "Periodic",
    false,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.PE.05",
    "Labor Variance Analysis",
    "Period End",
    "Periodic",
    false,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.PE.06",
    "Inventory Variance Capitalization",
    "Period End",
    "Periodic",
    true,
    "Preventive",
    "Manual with IT Dependency",
  ],
  [
    "INV.PE.07",
    "Inventory Reserve Calculation and Review",
    "Period End",
    "Quarterly",
    true,
    "Preventive",
    "Manual with IT Dependency",
  ],
  [
    "INV.PE.08",
    "Co-Man/Co-Pack Inventory Reserve Calculation and Review",
    "Period End",
    "Quarterly",
    true,
    "Preventive",
    "Manual with IT Dependency",
  ],
  [
    "INV.RG.01",
    "Review of Returned Goods",
    "Returned Goods",
    "Event Based",
    true,
    "Preventive",
    "Manual",
  ],
  [
    "INV.RG.02",
    "Returned Product Review",
    "Returned Goods",
    "Event Based",
    true,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.ST.01",
    "Review of Annual Standard Costs",
    "Standard Costs",
    "Annually",
    true,
    "Preventive",
    "Manual with IT Dependency",
  ],
  [
    "INV.ST.02",
    "Annual Inventory Revaluation",
    "Standard Costs",
    "Annually",
    true,
    "Preventive",
    "Manual with IT Dependency",
  ],
  [
    "INV.ST.03",
    "Update and Review of Standard Cost Changes",
    "Standard Costs",
    "Event Based",
    true,
    "Preventive",
    "Manual with IT Dependency",
  ],
  [
    "INV.MM.01",
    "Approval of Material Master Data Changes",
    "Material Master Data",
    "Event Based",
    true,
    "Preventive",
    "Manual",
  ],
  [
    "INV.MM.02",
    "Review of Material Master Data Changes",
    "Material Master Data",
    "Periodic",
    true,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.CV.01",
    "Purchase Price Variance Calculation and Posting",
    "Costing Variances",
    "Event Based",
    true,
    "Preventive",
    "Automated",
  ],
  [
    "INV.CV.02",
    "Production Variance Calculation and Posting",
    "Costing Variances",
    "Event Based",
    true,
    "Preventive",
    "Automated",
  ],
  [
    "INV.CT.01",
    "Factory Inventory Cycle Counts",
    "Inventory Counts",
    "Event Based",
    true,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.CT.02",
    "Warehouse Inventory Cycle Counts",
    "Inventory Counts",
    "Event Based",
    true,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.CT.03",
    "Inventory Cycle Count Completeness",
    "Inventory Counts",
    "Event Based",
    true,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.CT.04",
    "Factory Physical Inventory Counts",
    "Inventory Counts",
    "Annually",
    true,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.CT.05",
    "Warehouse Physical Inventory Counts",
    "Inventory Counts",
    "Annually",
    true,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.CT.07",
    "Factory Physical Inventory Count Adjustments",
    "Inventory Counts",
    "Event Based",
    true,
    "Detective",
    "Manual",
  ],
  [
    "INV.CT.08",
    "Warehouse Physical Inventory Count Adjustments",
    "Inventory Counts",
    "Event Based",
    true,
    "Detective",
    "Manual",
  ],
  [
    "INV.WM.01",
    "Third Party Warehouse/Distribution Center Reconciliation",
    "Warehouse Management",
    "Periodic",
    true,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.WM.02",
    "Third Party Warehouse Physical Count Performance and Adjustments",
    "Warehouse Management",
    "Annually",
    true,
    "Detective",
    "Manual",
  ],
  [
    "INV.PM.01",
    "Co-Man/Co-Pack Physical Inventory Counts",
    "Co-Manufacturer / Co-Packer",
    "Annually",
    true,
    "Detective",
    "Manual",
  ],
  [
    "INV.SI.01",
    "Review of Supplier Owned/Consigned Inventories",
    "Supplier Owned Inventory",
    "Periodic",
    false,
    "Detective",
    "Manual",
  ],
  [
    "INV.AJ.01",
    "Inventory Write-offs and Disposals",
    "Inventory Adjustments",
    "Event Based",
    true,
    "Preventive",
    "Manual",
  ],
  [
    "INV.AJ.02",
    "Inventory Adjustments Review",
    "Inventory Adjustments",
    "Periodic",
    false,
    "Detective",
    "Manual",
  ],
  [
    "INV.AJ.03",
    "Inventory Valuation Process",
    "Inventory Adjustments",
    "Event Based",
    true,
    "Preventive",
    "Manual",
  ],
  [
    "INV.AJ.04",
    "Reserve Adjustments to Inventory Valuation",
    "Inventory Adjustments",
    "Periodic",
    true,
    "Detective",
    "Manual",
  ],
  [
    "INV.SM.01",
    "ERP and Warehouse Management System Reconciliation",
    "System Reconciliation",
    "Periodic",
    true,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.SH.01",
    "Review of Goods and Invoices Issued and Released",
    "Shipping",
    "Periodic",
    false,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.SH.02",
    "Finished Goods Review for Shipment",
    "Shipping",
    "Event Based",
    false,
    "Preventive",
    "Manual",
  ],
  [
    "INV.SH.03",
    "Preparation of Supporting Shipment Documentation",
    "Shipping",
    "Event Based",
    false,
    "Preventive",
    "Manual",
  ],
  [
    "INV.SA.01",
    "Spare Parts Physical Inventory Counts",
    "Spare Parts",
    "Annually",
    false,
    "Detective",
    "Manual",
  ],
  [
    "INV.SA.02",
    "Receipt, Movement and Usage of Spare Parts",
    "Spare Parts",
    "Event Based",
    true,
    "Preventive",
    "Manual",
  ],
  [
    "INV.SA.03",
    "Spare Part Re-order and Review",
    "Spare Parts",
    "Event Based",
    true,
    "Preventive",
    "Manual with IT Dependency",
  ],
  [
    "INV.BS.01",
    "Performance of Balance Sheet Account Reconciliations",
    "Balance Sheet",
    "Periodic",
    true,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.SD.01",
    "Segregation of Duties Review",
    "Segregation of Duties",
    "Semi-Annual",
    true,
    "Detective",
    "Manual with IT Dependency",
  ],
  [
    "INV.SO.01",
    "Reliance on Outsourced Financial Controls",
    "SOC 1 / SSAE 18",
    "Annually",
    true,
    "Detective",
    "Manual",
  ],
  [
    "INV.PD.01",
    "Local Inventory Process Documentation and Desktop Procedures Review",
    "Process Documentation",
    "Annually",
    true,
    "Preventive",
    "Manual",
  ],
];

export const inventoryControls: InventoryControl[] = controlRows.map(
  ([id, name, process, frequency, keyControl, nature, type]) => ({
    id,
    name,
    process,
    frequency,
    keyControl,
    nature,
    type,
    evidenceRequired: ![
      "INV.MF.03",
      "INV.RV.03",
      "INV.PE.02",
      "INV.RG.01",
      "INV.CV.01",
      "INV.CV.02",
      "INV.CT.03",
      "INV.SH.01",
      "INV.SH.02",
      "INV.SA.02",
      "INV.SA.03",
    ].includes(id),
    owner: "Unassigned",
    status: "Unassigned",
    due: "Not scheduled",
    dtpStatus: "Not added",
    region: "Europe",
    site: "",
    unit: "Food & Nutrition",
    instructions: "",
  }),
);

export const processCounts = Array.from(
  new Set(inventoryControls.map((control) => control.process)),
)
  .map((process) => ({
    process,
    count: inventoryControls.filter((control) => control.process === process)
      .length,
  }))
  .sort((a, b) => b.count - a.count);
